/**
 * TEAM ROSTER — the thirty-three people of the department.
 *
 *   Project Management   — 15 people
 *   Process & Procedures — 11 people
 *   BPT & Testing        —  7 people
 *   TOTAL                — 33 people
 *
 * Names, roles and biographies come from the content workbook by way of
 * `ppmd-content/workbookContent`, which is generated by
 * `scripts/import-content.mjs`. Nothing descriptive is written here.
 *
 * Portraits do NOT come from the workbook: its `photo_filename` column is
 * empty, and the files under `public/people/` are the real photographs.
 * So this module holds one table — id, portrait file — and joins the
 * workbook's content onto it. That join is by workbook id rather than by
 * name on purpose: it is the one thing that stays stable when a name is
 * respelled, and the site ids are also what the spatial compositions seat
 * people by.
 *
 * Some of the workbook's descriptive columns are still sample text. The
 * importer withholds those, so those records simply arrive without a
 * biography and every surface already omits a field it is not given. A
 * profile then shows the portrait, the name, the role and the team —
 * which is what is actually known about that person.
 *
 * The Senior Director and the Senior Manager who leads the department
 * live in leadershipData.ts and are NOT part of this roster.
 */
import { WB_PEOPLE } from '../ppmd-content/workbookContent'
import type { Person, PersonLevel } from './peopleTypes'
import { PORTRAIT_FOCUS } from './portraitFraming'

const PORTRAITS = `${import.meta.env.BASE_URL}people/`

const TEAM_ACCENTS: Record<string, string> = {
  'Project Management': '#ff6e79',
  'Process & Procedures': '#e8c188',
  'BPT & Testing': '#7cc4ff',
}

/** Workbook team names → the shorter names the site composes around. */
const TEAM_KEYS: Record<string, string> = {
  'Project Management Team': 'Project Management',
  'Process & Procedures Management Team': 'Process & Procedures',
  'BPT & Testing Team': 'BPT & Testing',
}

/** Leadership functions per team (Team Leader + programme-manager tier). */
export const TEAM_LEADERSHIP_EXPECTED: Record<string, number> = {
  'Project Management': 3,
  'Process & Procedures': 1,
  'BPT & Testing': 1,
}

/** Team sizes, as stated by the workbook and by the portrait folders. */
export const TEAM_SIZE_EXPECTED: Record<string, number> = {
  'Project Management': 15,
  'Process & Procedures': 11,
  'BPT & Testing': 7,
}
export const TOTAL_EXPECTED = 33

/**
 * The site's own id for each person, and their photograph.
 *
 * Written out rather than derived from the name, because a slug of the
 * name is not stable: the workbook spells the Process & Procedures team
 * leader "Desislava Mihaylova" while her portrait file and every seat
 * that references her say "Mihalova". Deriving the id would have silently
 * unseated her from the composition and dropped her photograph. The
 * displayed NAME follows the workbook; the id and the file do not.
 */
const ASSETS: Record<string, { id: string; photo: string }> = {
  'PM-001': { id: 'PM-dragomir-apostolov', photo: 'project-management/Dragomir-Apostolov_team-leader.jpeg' },
  'PM-002': { id: 'PM-petar-rusinov', photo: 'project-management/Petar-Rusinov_Business-projects-management-manager.jpg' },
  'PM-003': { id: 'PM-valentin-stoev', photo: 'project-management/Valentin-Stoev_Technology-projects-management-manager.jpeg' },
  'PM-004': { id: 'PM-mariela-mincheva', photo: 'project-management/Mariela-Mincheva_Senior-Project-Manager.jpg' },
  'PM-005': { id: 'PM-aneliya-panayotova', photo: 'project-management/Aneliya-Panayotova_Project-Manager.jpg' },
  'PM-006': { id: 'PM-vesela-grigorova', photo: 'project-management/Vesela-Grigorova_Project-Manager.jpg' },
  'PM-007': { id: 'PM-veselin-slavkov', photo: 'project-management/Veselin-Slavkov_Project-Manager.jpg' },
  'PM-008': { id: 'PM-danaya-georgieva', photo: 'project-management/Danaya-Georgieva_Project-Manager.jpg' },
  'PM-009': { id: 'PM-yordanka-meshova', photo: 'project-management/Yordanka-Meshova_Project-Manager.jpg' },
  'PM-010': { id: 'PM-maya-atanasova', photo: 'project-management/Maya-Atanasova_Project-Manager.jpg' },
  'PM-011': { id: 'PM-mila-vladova', photo: 'project-management/Mila-Vladova_Project-Manager.jpg' },
  'PM-012': { id: 'PM-hristina-shotekova', photo: 'project-management/Hristina-Shotekova_Project-Manager.jpg' },
  'PM-013': { id: 'PM-yana-nikolova', photo: 'project-management/Yana-Nikolova_Project-Manager.jpg' },
  'PM-014': { id: 'PM-emil-savov', photo: 'project-management/Emil-Savov_Junior-Project-Manager.png' },
  'PM-015': { id: 'PM-donna-rakov', photo: 'project-management/Donna-Rakov_Junior-Project-Manager.jpg' },

  'PROC-001': { id: 'PROC-desislava-mihalova', photo: 'process-procedures-management/Desislava-Mihalova_Team-Leader.webp' },
  'PROC-002': { id: 'PROC-anna-ilieva', photo: 'process-procedures-management/Anna-Ilieva.jpg' },
  'PROC-003': { id: 'PROC-tatyana-stoyneva', photo: 'process-procedures-management/Tatyana-Stoyneva.png' },
  'PROC-004': { id: 'PROC-galina-gekova', photo: 'process-procedures-management/Galina-Gekova.png' },
  'PROC-005': { id: 'PROC-elitsa-tsvetanova', photo: 'process-procedures-management/Elitsa-Tsvetanova.png' },
  'PROC-006': { id: 'PROC-kameliya-dakova', photo: 'process-procedures-management/Kameliya-Dakova.png' },
  'PROC-007': { id: 'PROC-mariya-grigorova', photo: 'process-procedures-management/Mariya-Grigorova.webp' },
  'PROC-008': { id: 'PROC-simona-yordanova', photo: 'process-procedures-management/Simona-Yordanova_Senior-Specialist.webp' },
  'PROC-009': { id: 'PROC-bozhidara-stoilova', photo: 'process-procedures-management/Bozhidara-Stoilova_Senior-Specialist.webp' },
  'PROC-010': { id: 'PROC-adelina-dotseva', photo: 'process-procedures-management/Adelina-Dotseva_Senior-Specialist.png' },
  'PROC-011': { id: 'PROC-mariela-ilieva', photo: 'process-procedures-management/Mariela-Ilieva_Specialist.webp' },

  'BPT-001': { id: 'BPT-ivan-rumenov', photo: 'bpt-testing/Ivan-Rumenov_Team-lead.png' },
  'BPT-002': { id: 'BPT-kaloyan-dzhokin', photo: 'bpt-testing/Kaloyan-Dzhokin_Expert.jpeg' },
  'BPT-003': { id: 'BPT-luka-tsekov', photo: 'bpt-testing/Luka-Tsekov_Senior-Specialist.jpeg' },
  'BPT-004': { id: 'BPT-mariya-tudakova', photo: 'bpt-testing/Mariya-Tudakova_Senior-Specialist.jpg' },
  'BPT-005': { id: 'BPT-martin-chalev', photo: 'bpt-testing/Martin-Chalev_Specialist.jpg' },
  'BPT-006': { id: 'BPT-nadezhda-peycheva', photo: 'bpt-testing/Nadezhda-Peycheva_Senior-Specialist.jpg' },
  'BPT-007': { id: 'BPT-stoil-mortev', photo: 'bpt-testing/Stoil-Mortev_Senior-Specialist.jpg' },
}

/**
 * Two titles the site states more precisely than the workbook does.
 *
 * The workbook calls both coordinating managers "Program Manager". The
 * department's own portrait files name the jobs — Business projects
 * management manager, Technology projects management manager — and those
 * are the titles the site has been showing. Replacing a specific real
 * title with a generic one is a loss of content rather than an update, so
 * the specific form is kept and the difference is reported rather than
 * resolved silently.
 */
const ROLE_OVERRIDES: Record<string, string> = {
  'PM-002': 'Business Projects Management Manager',
  'PM-003': 'Technology Projects Management Manager',
}

/**
 * A title that has not been confirmed yet. Held as a constant because two
 * places have to agree about it: the record, and every surface that has to
 * decide whether there is a role to print.
 */
export const ROLE_UNCONFIRMED = 'Role to be confirmed'

/**
 * The role as it should be displayed, or nothing.
 *
 * "Role to be confirmed" is a note about the data, not a job. Printed
 * under a portrait or inside a profile it tells the reader nothing about
 * the person and reads as filler, so the line is left out instead — the
 * layouts all treat the role as optional.
 */
export function displayRole(p: Person): string | undefined {
  return !p.role || p.role === ROLE_UNCONFIRMED ? undefined : p.role
}

/** Team Leader, coordinating manager, or colleague. */
function levelOf(isLeadership: boolean, leadershipOrder?: number): PersonLevel {
  if (!isLeadership) return 'team-member'
  return leadershipOrder === 1 ? 'team-lead' : 'program-manager'
}

export const PEOPLE: Person[] = WB_PEOPLE.flatMap((w) => {
  const asset = ASSETS[w.id]
  const team = TEAM_KEYS[w.team ?? '']
  /* A workbook record with no portrait table entry, or on a team this
     site does not compose, is not silently half-rendered. It is left out
     and reported by `validatePeopleData` below. */
  if (!asset || !team) return []
  return [
    {
      id: asset.id,
      name: w.name ?? asset.id,
      role: ROLE_OVERRIDES[w.id] ?? w.role ?? ROLE_UNCONFIRMED,
      team,
      photo: `${PORTRAITS}${asset.photo}`,
      photoAlt: w.photoAlt ?? `Portrait of ${w.name ?? ''}`.trim(),
      /* The workbook says "center" for every portrait, which is the value
         it was pre-filled with rather than a decision about these images.
         These sources are small upright shots with the face high in
         frame, and the house focal point is set for exactly that — see
         portraitFraming. */
      photoPosition: PORTRAIT_FOCUS,
      shortBio: w.shortBio,
      shortBioEmphasis: w.shortBioEmphasis,
      keyContribution: w.keyContribution,
      keyContributionEmphasis: w.keyContributionEmphasis,
      personalFact: w.personalFact,
      personalFactEmphasis: w.personalFactEmphasis,
      accent: TEAM_ACCENTS[team],
      isLeadership: w.isLeadership,
      leadershipLevel: levelOf(w.isLeadership, w.leadershipOrder),
      leadershipOrder: w.leadershipOrder,
      displayOrder: w.displayOrder,
    },
  ]
})

/** Team roster, leadership first, then exact display order. */
export function peopleByTeam(team: string): Person[] {
  return PEOPLE.filter((p) => p.team === team).sort((a, b) => {
    if (a.isLeadership !== b.isLeadership) return a.isLeadership ? -1 : 1
    if (a.isLeadership && b.isLeadership) {
      return (a.leadershipOrder ?? 99) - (b.leadershipOrder ?? 99)
    }
    return a.displayOrder - b.displayOrder
  })
}

export function teamCount(team: string): number {
  return PEOPLE.filter((p) => p.team === team).length
}

/**
 * Development-time sanity check: warns (never throws) when the roster
 * disagrees with the structure above. Safe in production.
 */
export function validatePeopleData(): void {
  const ids = new Set<string>()
  for (const p of PEOPLE) {
    if (ids.has(p.id)) console.warn(`[peopleData] Duplicate person id: ${p.id}`)
    ids.add(p.id)
  }
  if (PEOPLE.length !== WB_PEOPLE.length) {
    console.warn(
      `[peopleData] ${WB_PEOPLE.length} people in the workbook, ${PEOPLE.length} placed. ` +
        'A record with no portrait-table entry is not rendered.',
    )
  }
  if (PEOPLE.length !== TOTAL_EXPECTED) {
    console.warn(`[peopleData] Total roster is ${PEOPLE.length}, expected ${TOTAL_EXPECTED}.`)
  }
  for (const [team, expected] of Object.entries(TEAM_SIZE_EXPECTED)) {
    const actual = teamCount(team)
    if (actual !== expected) {
      console.warn(`[peopleData] ${team}: ${actual} people, expected ${expected}.`)
    }
  }
  for (const [team, expected] of Object.entries(TEAM_LEADERSHIP_EXPECTED)) {
    const actual = PEOPLE.filter((p) => p.team === team && p.isLeadership).length
    if (actual !== expected) {
      console.warn(
        `[peopleData] ${team}: ${actual} leadership function(s), expected ${expected}.`,
      )
    }
  }
}
